<ul class="nav pull-right logged-out list-unstyled medium-right-margin">
      <li id="sign_up" class="pull-left medium-right-margin"> <a data-signup-modal="" data-header-view="true" href="testimonials.html" class="link-reset" rel="nofollow" onmouseover="this.style.backgroundColor = '#e2227c';" onmouseout="this.style.backgroundColor = 'inherit';"> Testimonials </a> </li>
<!--      <li id="sign_up" class="pull-left medium-right-margin"> <a data-signup-modal="" data-header-view="true" href="press.html" class="link-reset" rel="nofollow" onmouseover="this.style.backgroundColor = '#e2227c';" onmouseout="this.style.backgroundColor = 'inherit';"> Press </a> </li>-->
      <li id="sign_up" class="pull-left medium-right-margin"> <a data-signup-modal="" data-header-view="true" href="link.html" class="link-reset" rel="nofollow" onmouseover="this.style.backgroundColor = '#e2227c';" onmouseout="this.style.backgroundColor = 'inherit';"> Link </a> </li>
      <li id="sign_up" class="pull-left medium-right-margin">
       <a data-signup-modal="" data-header-view="true" href="about-us.html" class="link-reset" rel="nofollow" onmouseover="this.style.backgroundColor = '#e2227c';" onmouseout="this.style.backgroundColor = 'inherit';"> About Us </a> </li>
      <li id="sign_up" class="pull-left medium-right-margin"> <a data-signup-modal="" data-header-view="true" href="faq.html" class="link-reset" rel="nofollow" onmouseover="this.style.backgroundColor = '#e2227c';" onmouseout="this.style.backgroundColor = 'inherit';"> Faq </a> </li>
      
       <li id="login" class="pull-left medium-right-margin"> <a data-login-modal="" href="gallery.html" class="link-reset" rel="nofollow" onmouseover="this.style.backgroundColor = '#e2227c';" onmouseout="this.style.backgroundColor = 'inherit';">Gallery</a> </li>
        <li id="login" class="pull-left medium-right-margin"> <a data-login-modal="" href="news.html" class="link-reset" rel="nofollow" onmouseover="this.style.backgroundColor = '#e2227c';" onmouseout="this.style.backgroundColor = 'inherit';">News</a> </li>
        <li id="login" class="pull-left"> <a data-login-modal="" href="contact.html" class="link-reset" rel="nofollow" onmouseover="this.style.backgroundColor = '#e2227c';" onmouseout="this.style.backgroundColor = 'inherit';">Contact</a> </li>
    </ul>